version: '3.9'

services:

  postgres:
    image: pgvector/pgvector:pg17
    container_name: cloud-optimizer-db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data
  
    networks:
      - cloud-optimizer-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  


  redis:
    image: redis:7-alpine
    container_name: cloud-optimizer-redis
    restart: unless-stopped

    volumes:
      - redis-data:/data

    command: redis-server --appendonly yes

    networks:
      - cloud-optimizer-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  


  backend:
    image: manishk57107/cloud-optimizer-backend:latest
    container_name: cloud-optimizer-backend
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8081:8081"

    environment:
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      - postgres
      - redis

    networks:
      - cloud-optimizer-network



  frontend:
    image: manishk57107/cloud-optimizer-frontend:latest
    container_name: cloud-optimizer-frontend
    restart: unless-stopped

    ports:
      - "80:8080"

    depends_on:
      - backend

    networks:
      - cloud-optimizer-network



networks:
  cloud-optimizer-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: